class loginPage():
    email = 'Email'
    psw = 'Password'
    login_btn = '//input[@class="button-1 login-button"]'
    err_msg = '//div[@class="validation-summary-errors"]'

class loginData():
    url = 'https://demowebshop.tricentis.com/'
    url_regist = 'https://demowebshop.tricentis.com/register'
    url_login = 'https://demowebshop.tricentis.com/login'
    title = 'Demo Web Shop'
    email_valid = 'sel@test.com'
    psw_valid = '123456'
    email_invalid = 'tested@test.com'
    psw_invalid = "098765"
    msg_error_login = 'Login was unsuccessful.'


class CheckOutPage():
    add_cart_btn = '//input[@class="button-2 product-box-add-to-cart-button"]'
    go_to_cart = '//span[@class="cart-label"]'
    rec_name = 'giftcard_2_RecipientName'
    rec_email = 'giftcard_2_RecipientEmail'
    snd_name = 'giftcard_2_SenderName'
    snd_email = 'giftcard_2_SenderEmail'
    add_cart_btn2 = '//input[@class="button-1 add-to-cart-button"]'
    tns = 'termsofservice'
    co_guest_btn = '//input[@class="button-1 checkout-as-guest-button"]'
    co_btn = '//button[@id="checkout"]'
    ctn_btn = '//button[@class="button-2 order-completed-continue-button]'

class CheckOutData():
    url = 'https://demowebshop.tricentis.com/'
    url_VGC ='https://demowebshop.tricentis.com/25-virtual-gift-card'
    url_cart = 'https://demowebshop.tricentis.com/cart'
    url_complete = 'https://demowebshop.tricentis.com/checkout/completed/'
    title = 'Demo Web Shop'
    rec_name_valid = 'Nama Penerima'
    rec_email_valid = 'penerima@email.com'
    snd_name_valid = 'Test Selenium'
    snd_email_valid = 'sel@test.com'
    order_no = 'Order Number'

class BillingPage():
    First_Name = 'BillingNewAddress_FirstName'
    Last_Name = 'BillingNewAddress_LastName'
    Email = 'BillingNewAddress_Email'
    Company = 'BillingNewAddress_Company'
    Country = 'BillingNewAddress_CountryId'
    State = 'BillingNewAddress_StateProvinceId'
    City = 'BillingNewAddress_City'
    Address1 = 'BillingNewAddress_Address1'
    Address2 = 'BillingNewAddress_Address2'
    ZipCode = 'BillingNewAddress_ZipPostalCode'
    Ph_No = 'BillingNewAddress_PhoneNumber'
    Fax_no = 'BillingNewAddress_FaxNumber'
    cnt_btn = '//input[@title="Continue"]'
    COD_rad = '//input[@value="Payments.CashOnDelivery"]'
    cnt_btn_pm = '//input[@class="button-1 payment-method-next-step-button"]'
    cnt_btn_pi = '//input[@class="button-1 payment-info-next-step-button"]'
    confirm_btn = '//input[@class="button-1 confirm-order-next-step-button"]'

class BillingData():
    Bill_First_Name = 'Test'
    Bill_Last_Name = 'Selenium'
    Bill_Company = 'Company'
    Bill_Country = 'JPN'
    Bill_State = 'Other (Non US)'
    Bill_City = 'Tokyo'
    Bill_Address1 = 'St Regist'
    Bill_Address2 = 'No 12'
    Bill_ZipCode = '12345'
    Bill_Ph_No = '12345678'
    Bill_Fax_no = '23456789'

